name: echidna

author: JP Smith

version: 0.0.0.1

ghc-options: -Wall -fno-warn-orphans -O2

dependencies:
  - aeson                >= 1.3    && < 1.5
  - base
  - ansi-terminal
  - bytestring           >= 0.10.8 && < 0.11
  - containers           >= 0.5.7  && < 0.6
  - data-dword           >= 0.3.1  && < 0.4
  - deepseq
  - directory            >= 1.3    && < 1.4
  - exceptions           >= 0.8.1  && < 0.11
  - hedgehog             >= 0.6
  - hashable
  - hevm
  - lens                 >= 4.15.1 && < 4.17
  - mtl                  >= 2.2.1  && < 2.3
  - multiset             >= 0.3    && < 0.4
  - optparse-applicative >= 0.13.0 && < 0.15
  - process              >= 1.4.3  && < 1.7
  - stm
  - temporary            >= 1.2.1  && < 1.4
  - text                 >= 1.2.2  && < 1.3
  - transformers
  - vector               >= 0.11.0 && < 0.13
  - wl-pprint-annotated
  - yaml
  - unordered-containers
      
default-extensions:
  - OverloadedStrings

library:
  source-dirs: lib/
  exposed-modules:
    - Echidna.ABI
    - Echidna.Config
    - Echidna.Coverage
    - Echidna.Event
    - Echidna.Exec
    - Echidna.Output
    - Echidna.Solidity
    - Echidna.Property

executables:
  echidna-test:
    main: Main.hs
    source-dirs: src/
    dependencies: echidna

  perprop-exe:
    main: Main.hs
    source-dirs: perprop
    dependencies: echidna
